language: php
dist: trusty

sudo: false

cache:
    directories:
    - vendor
    - $HOME/.composer/cache

php:
    - 7.0
    - 7.1
    - 7.2
    - nightly

notifications:
    email: false
    irc:
      channels:
        - "irc.iiens.net#Erebot"
      on_success: change
      on_failure: always

before_script:
    - rm composer.lock
    - composer self-update -n
    - composer install -n
    - vendor/bin/wordlist-converter tests/wordlists/test.txt
    - vendor/bin/wordlist-converter tests/wordlists/twowords.txt

script:
    - vendor/bin/phpunit --coverage-clover clover.xml
    - vendor/bin/phpcs

after_success:
    - composer require --dev satooshi/php-coveralls
    - travis_retry vendor/bin/php-coveralls -n -v

jobs:
  include:
    - stage: deploy
      name: "Documentation"
      script:
        - git clone --depth=1 --branch=build https://github.com/Erebot/erebot.github.io.git docs/trigger
        - "export TRIGGER_DOC_BUILD=$( (git show --pretty=format: --name-only $TRAVIS_COMMIT | grep -q '^docs/' && echo 1) || echo 0 )"
      deploy:
        provider: pages
        local-dir: docs/trigger
        repo: Erebot/erebot.github.io
        target-branch: trigger
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: false
        allow-empty-commit: true
        verbose: true
        on:
          all_branches: true
          condition: '$TRIGGER_DOC_BUILD -eq 1 -a $TRAVIS_PULL_REQUEST= "false"'
